deploy:
  provider: lambda
  runtime: node
  function_name: CountrySkill
  role: arn:aws:iam::503962799038:role/service-role/lambda_basic_execution
  handler_name: index.handler
  access_key_id: AKIAI5WB7PSPZPAVO3YA
  secret_access_key:
    secure: eblslwZ9jbRDVqZldBeaGedwKxU9A1kgn2hWFFqQzJNwmiz45/1U1KNhJqfHlSDmpgE/HB5aFatxqMIEztaetgJmz2qpTMpOGUO6AYZ6gdzxpdcS0S1sKz/5JDkng7pX4pwwCUxYeW6Yw4Y4cjEyXBk/4PXu5u+jXKQ11kJ3y3KJ/Eg7ipOSqqc4blXxPemOETudw6bxemCDOJhHHo7I1G7QI4imjbqRkHxkvPW+7R6i1QCZUiCQrnWiF6meAn/yDOQxz4WxyCDR1eAJpO8C+dDKd4NfIku38B3NJa033kF+fLFsbeNcwJUIEWpZ0L4DuUx86+a18svfbrP6eqREaY9NyWryf8bw7qzv8iNLavcIVSDShSY/WQJ4o1oXzsRs62tH55fMOsqOqe3/pykYbFx6cm7Xa1UjVyOxXXcMiJMHRRKTirofghUyE3+IAtZ1SB6a/b5ePCRLbEruKyy73iFnb6Q8OjrbDN4g/m7OFAU3xWBP1F8X1/ujQGplIfmOzFlebZ97s/SdzeTAVMmBGVDAYABHV+zlwrIU7g1hKtx8T8enEORXrYb6UJzlVJHjOWSmFCOU8koxaK3ZQYN9DWErHtEhWCr/nxGOciCJm6W8ulA5EuShwKF3cvWtBIoAcvum2RCGUymWNi7ULMsK4Kry2p4+N+XBMs4f943qFno=
  on:
    branch: release
